### ISSUE TITLE
code to read smart contract

### ISSUE THREAD

**Issue by vivekebics** [zupzup/react-native-ethereum#1]
Hi,
Can anyone share the code to smart contract?

**Comment by zupzup** [comment]
Which smart contract?

Or do you mean, how to interface with a smart contract from geth-android?

There is not much documentation unfortunately, most importantly this: https://github.com/ethereum/go-ethereum/wiki/Mobile:-Introduction

In general, when using geth for android, just look at the API of the Go-version of geth. The Android/iOS Versions are just cross-compiled using GoMobile, so the API for Java should be the same as from Go.

But there is no Javadoc available at the moment.

**Comment by vivekebics** [comment]
You have provided code to check the account balance information. We have deployed smart contract in ethereum network. I would like to use these lib to access the smart contracts.

**Comment by vivekebics** [comment]
Hi, I have geth-1.6.7.aar in android studio project. I am not able get   NodeHolder nh = NodeHolder.getInstance();. Do i need to import any other library ?

**Comment by zupzup** [comment]
The NodeHolder class is custom made, for handling state. It's checked in in this project.

**Comment by vivekebics** [comment]
Sorry, that was my blender.  to access the smart contract what are all the parameters do i need to use ?

**Comment by zupzup** [comment]
I haven't used the Android version for interacting with smart contracts yet, but I guess it's the same as with the Go version (which I described here: https://zupzup.org/eth-smart-contracts-go/), or with web3.

Basically you instantiate the contract from the address and then call it's methods.
