### ISSUE TITLE
 Zero Ether Found for given address 0x22B84d5FFeA8b801C0422AFe752377A64Aa738c2

### ISSUE THREAD

**Issue by vivekebics** [zupzup/react-native-ethereum#3]
I have checked in the main net for the given address **0x22B84d5FFeA8b801C0422AFe752377A64Aa738c2** we have some ether. But the alert dialog i get 0 ether found. Another doubt is i get new account address which is not the same given address '**0x22B84d5FFeA8b801C0422AFe752377A64Aa738c2**. Can you please help me to understand ?

![screenshot_1507187782](https://user-images.githubusercontent.com/29792642/31215438-1da24bb2-a9cd-11e7-9586-179d42cdd964.png)

**Comment by zupzup** [comment]
That's likely because you haven't synced the whole state - it takes quite some time (tooke me ~1 hour the first time). Once the latest block header are synced, the state should be correct

**Comment by vivekebics** [comment]
Okay. I understand. Do we have any option to indicate the user that nodes is syncing the GUI like showing progress bar or spinner options ?

**Comment by zupzup** [comment]
You would have to check the API - iirc there was a log-message in the log indicating the sync-progress.
If you take the same information and build a progress-bar out of it, that would probably work well I guess.

**Comment by vivekebics** [comment]
Sorry I am not able to understand. what is iirc - api ? Can you provide me some example to add in native and show in react native screen ?

**Comment by zupzup** [comment]
iirc = "if i recall correctly" ;)

I'm sorry, but I don't have the time or focus at the moment, but I'm sure you'll find some good examples and tutorials for react-native on the web

**Comment by vivekebics** [comment]
is these syncing correctly ?

 ```type=1400 audit(0.0:8133): avc: denied { read } for name="/" dev="tmpfs" ino=1051 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:device:s0 tclass=dir permissive=0```
